[project]
name = "groundstation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "board>=1.0",
    "foxglove-schemas-protobuf>=0.3.0",
    "foxglove-websocket>=0.1.2",
    "gpiozero>=2.0.1",
    "lz4>=4.4.4",
    "mcap>=1.2.2",
    "mcap-protobuf-support>=0.5.3",
    "numpy>=2.2.5",
    "opencv-python>=4.11.0.86",
    "protobuf>=6.30.2",
    "pyquaternion>=0.9.9",
    "split>=0.4",
    "zstandard>=0.23.0",
]
