[project]
name = "groundstation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "foxglove-websocket>=0.1.2",
    "gpiozero>=2.0.1",
    "mcap>=1.2.2",
    "opencv-python>=4.11.0.86",
]
