# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tom_packet.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10tom_packet.proto\x12\x04\x63pss\"f\n\tTomPacket\x12\"\n\x05state\x18\x01 \x01(\x0e\x32\x13.cpss.TwoStageState\x12\x10\n\x08latitude\x18\x02 \x01(\x03\x12\x11\n\tlongitude\x18\x03 \x01(\x03\x12\x10\n\x08\x61ltitude\x18\x04 \x01(\x01*H\n\rTwoStageState\x12\x08\n\x04IDLE\x10\x00\x12\t\n\x05READY\x10\x01\x12\x0b\n\x07LIFTOFF\x10\x02\x12\x08\n\x04MAXQ\x10\x03\x12\x0b\n\x07\x42URNOUT\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tom_packet_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TWOSTAGESTATE']._serialized_start=130
  _globals['_TWOSTAGESTATE']._serialized_end=202
  _globals['_TOMPACKET']._serialized_start=26
  _globals['_TOMPACKET']._serialized_end=128
# @@protoc_insertion_point(module_scope)
